[build]
  command = "npm run build"
  functions = "lambda"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[[redirects]]  
  from = "https://loudktown.netlify.com/*"
  to = "https://www.loudktown.com/:splat"
  status = 301

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
